id: 8c1c0d5b380747b786d88fcc878c517b
initial_creation_type: ocr
source_metadata:
  volumes:
    76706d72bd7d4e84a88ad9b7f7145217:
      base_file: v092.txt
      image_group_id: I1PD95938
      title: ''
      total_pages: 1484
      volume_number: 93
